### ISSUE TITLE
Converted SVG & best practice semantic

### ISSUE THREAD

**Issue by baucucu** [nanohop/sketch-to-react-native#21]
Hi,
Could you please share a correctly converted svg file, ready to be processed into a react native component?

-------
PS:
I think this is where the sketch team could focus their r&d to -> seamless (ux) design product.
The workflow is possible, it is just fragmented

**Comment by chrisachard** [comment]
@baucucu Oh sure - I just added one to the examples folder (I actually thought it was already in there; thanks for pointing that out):

https://github.com/nanohop/sketch-to-react-native/blob/master/examples/Log%20In%20Page.svg

We're working on a Sketch plugin, which (I think) will answer your other question as well - it will make the entire process more seamless, and the output will be much better, since we'll have access to more data and the actual assets as exported from Sketch.
