### ISSUE TITLE
Is it also available for react? Not native.

### ISSUE THREAD

**Issue by snz2** [nanohop/sketch-to-react-native#27]
Is it also available for react? Not native.
If not, why? Or will it be supported?

**Comment by chrisachard** [comment]
I started with React Native only, because there were fewer components to manage.  I eventually want to make it work with React, but I don't have a set timeline for that.  

Someone has made a first attempt at getting React for web to work here: https://github.com/nanohop/sketch-to-react-native/pull/14  so you could check that out for now.

**Comment by snz2** [comment]
Thanks for the reply. I cheer for you.
